### ISSUE TITLE
Circles error handling

### ISSUE THREAD

**Issue by samanamarasinghe** [sethpatum/integratedTest-v1#5]
Circles, keeps track of omission errors. Would it be worthwhile to keep track of commission errors (false positives)? My guess is not needed.

**Comment by samanamarasinghe** [comment]
On Circles task, the results pop up on the background of the task, makes it hard to read.  Can we put them on a white background so that they’re more visible? -Dan

**Comment by samanamarasinghe** [comment]
Make the unmarked or wrongly marked different colors (same color scheme as letter cancellation)

**Comment by 17lime** [comment]
Results are improved now to include false positives, and results no longer pop up
